version: 0.2
run-as: root
env:
  secrets-manager:
    DB_PASSWORD: laravel-app:DB_PASSWORD
phases:
  install:
    runtime-versions: 
      php: 7.4
    commands:
      - echo Installing...
  pre_build:
    commands:
      - mv .env.example .env
      - sed -i "s|APP_URL=http://127.0.0.1:8000/|APP_URL=http://35.167.215.144|" .env
      - sed -i "s|DB_HOST=127.0.0.1|DB_HOST=endpoint|" .env
      - sed -i "s|DB_PASSWORD=|DB_PASSWORD=$DB_PASSWORD|" .env
  build:
    commands:
      - composer install
artifacts:
  files:
    - "**/*"
    - echo Uploaded Artifacts

